# -*- coding: utf-8 -*-
"""Taylor series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f6vOr2nQIgWVXt7UN7i0YXqVjL6tnVkJ
"""

from sympy import *
from math import factorial as fact

x = symbols('x')
expr = log(x) + 7*(x**3)

n = 10
center = 1
x_val = 1.4
true_value = expr.subs(x, x_val)

cumulative_sum = 0

print('Iteración | Valor Acumulado | Error absoluto | Error relativo')

last_value = 0
for i in range(n):
  i_derivate = diff(expr, x, i).subs(x, center)
  val = (x_val-center)**i
  val *= i_derivate
  val /= fact(i)
  cumulative_sum += val
  abs_error = abs(cumulative_sum - true_value)
  relative_error = abs(cumulative_sum - last_value)
  last_value = cumulative_sum
  print('    %d           %.4f           %.4f        %.4f' % (i,cumulative_sum,abs_error, relative_error))